# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 417)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(390, 380, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 380, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 110, 311, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.leCliente = QtWidgets.QLineEdit(Dialog)
        self.leCliente.setGeometry(QtCore.QRect(130, 260, 151, 25))
        self.leCliente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.leCliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.leCliente.setObjectName("leCliente")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 121, 21))
        self.label_4.setObjectName("label_4")
        self.leCliente_2 = QtWidgets.QLineEdit(Dialog)
        self.leCliente_2.setGeometry(QtCore.QRect(130, 300, 151, 25))
        self.leCliente_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.leCliente_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leCliente_2.setAlignment(QtCore.Qt.AlignCenter)
        self.leCliente_2.setObjectName("leCliente_2")
        self.leCliente_3 = QtWidgets.QLineEdit(Dialog)
        self.leCliente_3.setGeometry(QtCore.QRect(130, 340, 151, 25))
        self.leCliente_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.leCliente_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leCliente_3.setAlignment(QtCore.Qt.AlignCenter)
        self.leCliente_3.setObjectName("leCliente_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Linha a ser editada"))
        self.pushButton.setText(_translate("Dialog", "Aplicar"))
        self.pushButton_2.setText(_translate("Dialog", "Cancelar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Endereco"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Telefone"))
        self.label_2.setText(_translate("Dialog", "Alterar nome"))
        self.label_3.setText(_translate("Dialog", "Alterar endereco"))
        self.label_4.setText(_translate("Dialog", "Alterar telefone"))
