# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 421)
        self.btnAplicar = QtWidgets.QPushButton(Dialog)
        self.btnAplicar.setGeometry(QtCore.QRect(480, 250, 89, 25))
        self.btnAplicar.setObjectName("btnAplicar")
        self.btnCancelar = QtWidgets.QPushButton(Dialog)
        self.btnCancelar.setGeometry(QtCore.QRect(380, 250, 89, 25))
        self.btnCancelar.setObjectName("btnCancelar")
        self.tableWidget_3 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 50, 321, 321))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(325, 50, 251, 192))
        self.tableView.setObjectName("tableView")
        self.btnProcurar = QtWidgets.QPushButton(Dialog)
        self.btnProcurar.setGeometry(QtCore.QRect(230, 10, 91, 31))
        self.btnProcurar.setObjectName("btnProcurar")
        self.lineColocar = QtWidgets.QLineEdit(Dialog)
        self.lineColocar.setGeometry(QtCore.QRect(340, 60, 221, 31))
        self.lineColocar.setObjectName("lineColocar")
        self.linePesquisa_2 = QtWidgets.QLineEdit(Dialog)
        self.linePesquisa_2.setGeometry(QtCore.QRect(90, 10, 121, 31))
        self.linePesquisa_2.setObjectName("linePesquisa_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 16, 71, 21))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(400, 380, 171, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btnProcurar_2 = QtWidgets.QPushButton(Dialog)
        self.btnProcurar_2.setGeometry(QtCore.QRect(0, 380, 91, 31))
        self.btnProcurar_2.setObjectName("btnProcurar_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAplicar.setText(_translate("Dialog", "Aplicar"))
        self.btnCancelar.setText(_translate("Dialog", "Cancelar"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Endereco"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Telefone"))
        self.btnProcurar.setText(_translate("Dialog", "Procurar"))
        self.label.setText(_translate("Dialog", "Pesquisa"))
        self.btnProcurar_2.setText(_translate("Dialog", "Redefinir"))
