# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmexcluir.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 422)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(360, 380, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidget_3 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 50, 411, 321))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.btnRedefinir = QtWidgets.QPushButton(Dialog)
        self.btnRedefinir.setGeometry(QtCore.QRect(0, 380, 91, 31))
        self.btnRedefinir.setObjectName("btnRedefinir")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 71, 31))
        self.label.setObjectName("label")
        self.linePesquisa_3 = QtWidgets.QLineEdit(Dialog)
        self.linePesquisa_3.setGeometry(QtCore.QRect(80, 10, 121, 31))
        self.linePesquisa_3.setObjectName("linePesquisa_3")
        self.btnProcurar = QtWidgets.QPushButton(Dialog)
        self.btnProcurar.setGeometry(QtCore.QRect(210, 10, 91, 31))
        self.btnProcurar.setObjectName("btnProcurar")
        self.btnExcluirTudo = QtWidgets.QPushButton(Dialog)
        self.btnExcluirTudo.setGeometry(QtCore.QRect(430, 330, 91, 31))
        self.btnExcluirTudo.setObjectName("btnExcluirTudo")
        self.btnAplicar = QtWidgets.QPushButton(Dialog)
        self.btnAplicar.setGeometry(QtCore.QRect(430, 50, 91, 31))
        self.btnAplicar.setObjectName("btnAplicar")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Endereco"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Telefone"))
        self.btnRedefinir.setText(_translate("Dialog", "Redefinir"))
        self.label.setText(_translate("Dialog", "Pesquisa"))
        self.btnProcurar.setText(_translate("Dialog", "Procurar"))
        self.btnExcluirTudo.setText(_translate("Dialog", "Excluir tudo"))
        self.btnAplicar.setText(_translate("Dialog", "Aplicar"))
